# Databricks notebook source
# MAGIC %md
# MAGIC ## 05 Check Run Status and Set Restart Flags
# MAGIC
# MAGIC **Pipeline:** GW CDA Claims (Practice) | **Step:** Source to ADLS File Copy
# MAGIC
# MAGIC **Purpose:** Determine whether the current pipeline run is a fresh run or a restart
# MAGIC of a previously failed run. Reads the last known status of the cycle and the Source
# MAGIC to ADLS step from Azure SQL and returns two flags to ADF:
# MAGIC
# MAGIC - `Truncate` — whether raw files should be overwritten (`Y`) or preserved (`N`)
# MAGIC - `Force_Truncate` — whether to force re-copy even if the Source to ADLS load previously failed (`Y`)
# MAGIC
# MAGIC | | Production | This Project |
# MAGIC |--|-----------|-------------|
# MAGIC | Azure SQL Auth | Key Vault secrets | Hardcoded connection values |
# MAGIC | Schema param | `config_schema` widget | `ASQL_SCHEMA` widget — same purpose |
# MAGIC | Cycle run SK | Derived by querying CYC_RUN_TBL | Passed directly as `CYC_RUN_SK` widget — simpler |
# MAGIC | Output | `dbutils.notebook.exit(json)` | Same |

# COMMAND ----------

# DBTITLE 1,Pipeline Parameters
# ADF passes these parameters to the notebook at runtime.
# Production approach: identical widget pattern, same parameter names except where noted.
#
# Parameters to create in the ADF pipeline:
#   Name          Type     Example value
#   -------------------------------------------------------
#   ASQL_SCHEMA   String   abc
#   STEP_SK_RAW   String   10110
#   CYC_RUN_SK    String   1         ← current cycle run SK returned by PROC_UPDATE_CYC_START
#   -------------------------------------------------------

dbutils.widgets.text("ASQL_SCHEMA", "")
asql_schema = dbutils.widgets.get("ASQL_SCHEMA")

dbutils.widgets.text("STEP_SK_RAW", "")
step_sk_raw = dbutils.widgets.get("STEP_SK_RAW")

# CYC_RUN_SK: the run instance SK generated by PROC_UPDATE_CYC_START for this run.
# ADF captures this from the Cycle Start Lookup activity output and passes it here.
dbutils.widgets.text("CYC_RUN_SK", "")
cyc_run_sk = dbutils.widgets.get("CYC_RUN_SK")

print(f"ASQL_SCHEMA : {asql_schema}")
print(f"STEP_SK_RAW : {step_sk_raw}")
print(f"CYC_RUN_SK  : {cyc_run_sk}")

# COMMAND ----------

# DBTITLE 1,Azure SQL Connection
# Production approach:
#   Server, database name, username, and password fetched from Azure Key Vault
#   via dbutils.secrets.get("testsecretkv2", <secret-name>).
#
# This project:
#   Values are hardcoded -- no Key Vault configured for this practice environment.

AsqldbServer   = "<your-sql-server>.database.windows.net"
AsqldbName     = "<your-database-name>"
AsqldbUserName = "<your-sql-username>"
AsqldbPassword = "<your-sql-password>"  # In production: dbutils.secrets.get("your-kv-scope", "AsqldbPassword")

url_Asql = (
    f"jdbc:sqlserver://{AsqldbServer};"
    f"databaseName={AsqldbName};"
    f"user={AsqldbUserName};password={AsqldbPassword};"
    "encrypt=true;trustServerCertificate=false;"
    "hostNameInCertificate=*.database.windows.net;"
    "loginTimeout=30;socketTimeout=60000"
)

print(f"Connecting to: {AsqldbServer} / {AsqldbName}")

# COMMAND ----------

# DBTITLE 1,Helper Function
def get_metadata(table_or_query: str, is_query: bool):
    """
    Read data from Azure SQL via Spark JDBC and return a Spark DataFrame.

    is_query=False: table_or_query is a table name  e.g. "abc.CYC_RUN_TBL"
                    Spark reads the entire table.
    is_query=True:  table_or_query is a SQL SELECT   e.g. "SELECT CYC_STS_CD FROM ..."
                    Spark runs the query and returns only those rows/columns.
    """
    option_key = "query" if is_query else "dbtable"
    return (
        spark.read
        .format("jdbc")
        .option("url", url_Asql)
        .option(option_key, table_or_query)
        .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")
        .option("queryTimeout", "60")
        .load()
    )

# COMMAND ----------

# DBTITLE 1,Read Run History from Azure SQL
# Read the status of the current cycle run from CYC_RUN_TBL.
cyc_run_df = get_metadata(
    f"SELECT CYC_STS_CD FROM {asql_schema}.CYC_RUN_TBL WHERE CYC_RUN_SK = {cyc_run_sk}",
    is_query=True
)
CYC_STS_CD = cyc_run_df.first()["CYC_STS_CD"]
print(f"CYC_STS_CD  : {CYC_STS_CD}")

# Read the status of the most recent Src->Raw step run for this cycle.
# ORDER BY DESC so first() gives the latest attempt if the step ran more than once.
step_run_df = get_metadata(
    f"SELECT TOP 1 STEP_STS_CD FROM {asql_schema}.STEP_RUN_TBL "
    f"WHERE STEP_SK = {step_sk_raw} AND CYC_RUN_SK = {cyc_run_sk} "
    f"ORDER BY STEP_RUN_SK DESC",
    is_query=True
)
STEP_STS_CD = step_run_df.first()["STEP_STS_CD"]
print(f"STEP_STS_CD : {STEP_STS_CD}")

# COMMAND ----------

# DBTITLE 1,Determine Truncate Flags
# Truncate flag — controls whether raw files are overwritten this run.
#
# Restart scenario reference:
#
#   Scenario                              CYC_STS_CD   STEP_STS_CD   Truncate
#   -----------------------------------   ----------   -----------   --------
#   Fresh / normal run                        I             I            Y
#   Src->Raw failed, restarting               F             F            N
#   Raw->Replica failed (Src->Raw done)       F             S            N
#   Any other state                           -             -            Y
#
# When Truncate=N, raw files from the previous attempt are preserved and
# the copy step is skipped — avoids re-copying files already in ADLS raw/.

if STEP_STS_CD == 'I' and CYC_STS_CD == 'I':
    Truncate = 'Y'
elif (STEP_STS_CD in ('F', 'S')) and CYC_STS_CD == 'F':
    Truncate = 'N'
else:
    Truncate = 'Y'

# Force_Truncate flag — forces re-copy of raw files even when Src->Raw previously failed.
# Set to Y only when Src->Raw itself failed (files may be partially written).
Force_Truncate = 'Y' if STEP_STS_CD == 'F' else 'N'

print(f"Truncate       : {Truncate}")
print(f"Force_Truncate : {Force_Truncate}")

# COMMAND ----------

# DBTITLE 1,Exit Notebook
import json

# Return Truncate and Force_Truncate to ADF as a JSON string.
# ADF reads this via the notebook activity output and uses the values
# as conditions in downstream activities.
result = json.dumps({"Truncate": Truncate, "Force_Truncate": Force_Truncate})
print(result)
dbutils.notebook.exit(result)